In [16]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_excel("Raw.Technical Support Dataset.xlsx")

In [23]:
df.head()

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,...,Resolution time,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude
0,Closed,1012,Low,Email,Feature request,1st line support,Kristos Westoll,2023-01-02 00:58:36,2023-01-04 00:58:36,2023-01-02 01:58:36,...,2023-01-04 00:31:51.694,Within SLA,2023-01-04 04:02:59.013,1.0,3.0,Custom software development,Tier 1,Republic of Ireland,53.094024,-8.019675
1,In progress,1013,High,Phone,Product setup,2nd line support,Adolpho Messingham,2023-01-02 07:27:25,2023-01-04 07:27:25,2023-01-02 07:29:25,...,NaT,SLA Violated,NaT,3.0,NaN,Other,Tier 2,Italy,43.036776,12.678565
2,Resolved,1014,Low,Chat,Purchasing and invoicing,1st line support,Bernard Beckley,2023-01-02 06:59:04,2023-01-03 06:59:04,2023-01-02 07:01:04,...,2023-01-02 22:45:32.974,Within SLA,NaT,2.0,NaN,Custom software development,Tier 1,Austria,47.696472,13.345735
3,Closed,1015,Medium,Email,Pricing and licensing,1st line support,Connor Danielovitch,2023-01-03 03:09:39,2023-01-05 03:09:39,2023-01-03 04:09:39,...,2023-01-04 14:32:34.979,Within SLA,2023-01-08 04:24:54.771,10.0,4.0,Ready to use Software,Tier 1,Spain,39.673370,-4.767726
4,Closed,1016,Low,Email,Product setup,1st line support,Kristos Westoll,2023-01-03 00:03:58,2023-01-05 00:03:58,2023-01-03 01:03:58,...,2023-01-04 12:03:05.986,Within SLA,2023-01-06 06:05:08.637,1.0,2.0,Other,Tier 1,Austria,47.696472,13.345735

In [25]:
df.shape

(2330, 22)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2330 entries, 0 to 2329
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Status                          2330 non-null   object
 1   Ticket ID                       2330 non-null   int64
 2   Priority                        2330 non-null   object
 3   Source                          2330 non-null   object
 4   Topic                           2330 non-null   object
 5   Agent Group                     2330 non-null   object
 6   Agent Name                      2330 non-null   object
 7   Created time                    2330 non-null   datetime64[ns]
 8   Expected SLA to resolve         2330 non-null   datetime64[ns]
 9   Expected SLA to first response  2330 non-null   datetime64[ns]
 10  First response time             2312 non-null   datetime64[ns]
 11  SLA For first response          2330 non-null   object
 12  Resolution time                 1912 non-null   datetime64[ns]
 13  SLA For Resolution              2330 non-null   object
 14  Close time                      1173 non-null   datetime64[ns]
 15  Agent interactions              2312 non-null   float64
 16  Survey results                  1173 non-null   float64
 17  Product group                   2330 non-null   object
 18  Support Level                   2330 non-null   object
 19  Country                         2330 non-null   object
 20  Latitude                        2330 non-null   float64
 21  Longitude                       2330 non-null   float64
dtypes: datetime64[ns](6), float64(4), int64(1), object(11)
memory usage: 400.6+ KB

In [27]:
df.columns

Index(['Status', 'Ticket ID', 'Priority', 'Source', 'Topic', 'Agent Group',
       'Agent Name', 'Created time', 'Expected SLA to resolve',
       'Expected SLA to first response', 'First response time',
       'SLA For first response', 'Resolution time', 'SLA For Resolution',
       'Close time', 'Agent interactions', 'Survey results', 'Product group',
       'Support Level', 'Country', 'Latitude', 'Longitude'],
      dtype='object')

In [29]:
date_cols = [
    "Created time", 
    "Expected SLA to resolve",
    "Expected SLA to first response", 
    "First response time",
    "Resolution time", 
    "Close time"]
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [30]:
#Creating First Response time in hours
df["FRT_hours"] = (
df["First response time"] - df["Created time"]
).dt.total_seconds() / 3600

In [32]:
#Checking for any negative numbers
negatives = df[df["FRT_hours"] < 0]
print(negatives.shape)
print(negatives[["Ticket ID", "Created time",
"First response time", "FRT_hours"]])

(2, 23)
     Ticket ID        Created time     First response time  FRT_hours
229       1288 2023-02-01 19:56:22 2023-02-01 01:10:53.759 -18.757845
892       2135 2023-05-18 05:54:00 2023-05-17 20:19:49.433  -9.569602

In [33]:
df["FRT_hours"].describe()
df.sort_values("FRT_hours").head(10)
df.sort_values("FRT_hours", ascending=False).head(10)

,Status,Ticket ID,Priority,Source,Topic,Agent Group,Agent Name,Created time,Expected SLA to resolve,Expected SLA to first response,...,SLA For Resolution,Close time,Agent interactions,Survey results,Product group,Support Level,Country,Latitude,Longitude,FRT_hours
1606,In progress,3041,Medium,Email,Purchasing and invoicing,2nd line support,Heather Urry,2023-09-06 02:31:53,2023-09-08 02:31:53,2023-09-06 03:31:53,...,SLA Violated,NaT,5.0,NaN,Ready to use Software,Tier 2,Slovenia,46.149166,14.986011,27.878784
187,Resolved,1236,Medium,Phone,Pricing and licensing,1st line support,Nicola Wane,2023-01-27 02:57:53,2023-01-29 02:57:53,2023-01-27 02:59:53,...,Within SLA,NaT,4.0,NaN,Ready to use Software,Tier 1,France,48.864716,2.349014,13.556988
259,Resolved,1331,Medium,Email,Purchasing and invoicing,1st line support,Nicola Wane,2023-02-07 18:37:55,2023-02-09 18:37:55,2023-02-07 19:37:55,...,Within SLA,NaT,9.0,NaN,Other,Tier 1,Slovenia,46.149166,14.986011,7.870852
172,Resolved,1221,Medium,Email,Bug report,2nd line support,Heather Urry,2023-01-25 15:29:35,2023-01-27 15:29:35,2023-01-25 16:29:35,...,Within SLA,NaT,1.0,NaN,Custom software development,Tier 2,Greece,39.368279,21.863141,7.833315
1016,Closed,2291,Medium,Email,Pricing and licensing,1st line support,Nicola Wane,2023-06-07 20:16:46,2023-06-09 20:16:46,2023-06-07 21:16:46,...,Within SLA,2023-06-10 16:33:19.930,1.0,4.0,Ready to use Software,Tier 1,Czech Republic,49.803763,15.474913,7.681201
442,Closed,1548,Medium,Email,Other,1st line support,Nicola Wane,2023-03-08 07:47:06,2023-03-10 07:47:06,2023-03-08 08:47:06,...,Within SLA,2023-03-15 20:16:12.640,4.0,2.0,Training and Consulting Services,Tier 1,Italy,43.036776,12.678565,7.665359
102,Resolved,1138,Low,Email,Product setup,2nd line support,Heather Urry,2023-01-17 01:30:29,2023-01-19 01:30:29,2023-01-17 02:30:29,...,Within SLA,NaT,1.0,NaN,Ready to use Software,Tier 2,Spain,39.673370,-4.767726,7.380851
1037,Closed,2323,Low,Email,Product setup,2nd line support,Heather Urry,2023-06-10 02:58:45,2023-06-12 02:58:45,2023-06-10 03:58:45,...,Within SLA,2023-06-16 15:31:34.137,2.0,5.0,Training and Consulting Services,Tier 2,France,48.864716,2.349014,7.362122
695,Closed,1884,High,Email,Bug report,2nd line support,Heather Urry,2023-04-19 13:35:20,2023-04-21 13:35:20,2023-04-19 14:35:20,...,Within SLA,2023-04-24 01:51:49.879,5.0,3.0,Custom software development,Tier 2,Spain,39.673370,-4.767726,7.273730
1135,Closed,2448,Low,Email,Other,2nd line support,Michele Whyatt,2023-06-26 22:38:22,2023-06-28 22:38:22,2023-06-26 23:38:22,...,Within SLA,2023-06-27 15:53:11.169,2.0,4.0,Ready to use Software,Tier 2,France,48.864716,2.349014,7.142386

In [34]:
#I first quantified how many there were and inspected them, so I could justify the decision rather than silently dropping data
before = df.shape[0]
df = df[df["FRT_hours"] >= 0]
after = df.shape[0]
print(f"Removed {before - after} invalid rows")

Removed 20 invalid rows

In [36]:
df.describe()                 
df["FRT_hours"].describe() 
df["Priority"].value_counts()

Priority
Low       1182
Medium     715
High       413
Name: count, dtype: int64

In [41]:
df["created_hour"] = df["Created time"].dt.hour

In [42]:
df["res_hours"] = (
df["Resolution time"] - df["Created time"]
).dt.total_seconds() / 3600

In [43]:
df["created_weekday"] = df["Created time"].dt.day_name()

In [44]:
# Created resolution hours column, Created weekday,Created Hour